version: '2.1'
services:

  php:
    image: krizius/php:7.3-apache
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - 7070:80
    networks:
      - web
    depends_on:
      node:
        condition: service_healthy

  node:
    image: node:8-stretch
    working_dir: /home/node/app
    volumes:
      - ./frontend:/home/node/app
    healthcheck:
      test: curl -sS http://127.0.0.1 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
    command: bash -c "npm install && npm build && node healthcheck.js"

networks:
  web:
    driver: bridge
