version: '2.1'
services:

  php:
    image: krizius/php:7.3-apache
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - 7070:80
    networks:
      - web

  node:
    image: node:8-stretch
    working_dir: /home/node/app
    volumes:
      - ./frontend:/home/node/app
    command: bash -c "npm install && npm start"

networks:
  web:
    driver: bridge
